# writer_agent.py

def run_writer_agent(context):
    # Get messages sent to the writer_agent
    writer_messages = context.get_messages_for("writer_agent")

    if not writer_messages:
        print("Writer Agent: No message found.")
        return

    last_message = writer_messages[0]
    summarized_content = last_message.payload.get("summarized_results", "No summarized results found.")
    topic = last_message.payload.get("topic", "AI")  # Grab topic if passed

    # Title based on topic
    title = f"Latest Updates in {topic}"

    # Construct plain article for debug/log
    article = f"""
📝 === Final Article by Writer Agent ===

Title: {title}

{summarized_content}

(Generated by your AI Writer Agent.)
    """
    print(article)

    # Construct HTML email content
    email_subject = f"🧠 Your Daily AI Digest: {topic}"
    email_body = f"""
    <html>
        <body style="font-family: Arial, sans-serif; line-height: 1.6;">
            <h2>{email_subject}</h2>
            <p>{summarized_content}</p>
            <br>
            <p style="font-size: small; color: gray;">Generated by MEMAT Agent System.</p>
        </body>
    </html>
    """

    # Save email content in context
    context.latest_email = {
        "subject": email_subject,
        "body": email_body
    }
