name: Run Weekly MEMAT Script at 10AM IST

on:
  schedule:
    - cron: '30 4 * * 1'  # ⏰ Every Monday at 4:30 AM UTC = 10:00 AM IST
  workflow_dispatch:        # Allows manual trigger from GitHub

jobs:
  run-memat:
    runs-on: ubuntu-latest

    env:  # ✅ Expose GitHub Secrets as Environment Variables
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      SERPAPI_API_KEY: ${{ secrets.SERPAPI_API_KEY }}
      AGENT_TASKFORCE_APP_PASSWORD: ${{ secrets.AGENT_TASKFORCE_APP_PASSWORD }}
      

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the MEMAT script
        run: python app.py

      - name: Debug Env Vars (Optional)
        if: failure()
        run: env
